### ISSUE TITLE
RateLimitExceed Error

### ISSUE THREAD

**Issue by mltrev23** [drunest/velora-subnet#29]
Validator gets rate limit exceeding error when sending request a couple of times.
Miner says it is receiving too many requests.
How to set the rate limit exceed manually?

Module server is internally created in core module in communex.
We know it is related to bucket but we don't have approach to fix it now.

**Comment by drunest** [comment]
we can use `--token-refill-rate-base-multiplier` field to set the rate limits.
currently, the default value is 13, it means we can call the miner 1 time per ip address of the validator
